version: "3"

services:
  seed:
    build: ./web
    container_name: seed
#    restart: always
#    ports:
#      - 5000:5000
    command: gunicorn -k gevent -c gun.py manager:app

  nginx:
    build: ./nginx
    container_name: nginx
#    restart: always
    ports:
      - 80:80
    depends_on:
      - seed
